sudo: required
language: c
services:
  - docker

env:
  - DIST_NAME: ubuntu
    DIST_VERS: 16.04
#  - DIST_NAME: ubuntu
#    DIST_VERS: 14.04
#  - DIST_NAME: ubuntu
#    DIST_VERS: 12.04

services:
  - docker

before_install:
  - sudo docker pull ${DIST_NAME}:${DIST_VERS}
  - sudo docker build --rm=true --file=ci/DockerFile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:liblightnvm ci

script:
  - DOCKER_ID=$(mktemp)
  - sudo docker run --detach ${DIST_NAME}-${DIST_VERS}:liblightnvm > "${DOCKER_ID}"
  - sudo docker stop "$(cat ${DOCKER_ID})"
