sudo: required
language: c
services:
  - docker

env:
  - DIST_NAME: ubuntu
    DIST_VERS: 16.04
    TAG: liblightnvm
#  - DIST_NAME: ubuntu
#    DIST_VERS: 14.04
#  - DIST_NAME: ubuntu
#    DIST_VERS: 12.04

before_install:
  - docker pull ${DIST_NAME}:${DIST_VERS}
  - docker build --rm=true --file=ci/DockerFile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} .
  - docker run --name ${TAG} -d ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash

script:
  - docker exec -d ${TAG} hostname
  - docker exec -d ${TAG} ls
  - docker exec -d ${TAG} echo '22' > test
  - docker cp /workdir/test .
  - cat test
  #- DOCKER_ID_FILE=$(mktemp)
  #- docker run -d ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash > "${DOCKER_ID_FILE}"
  #- DOCKER_ID=$(cat ${DOCKER_ID_FILE})
  #- docker ps -a
  #- docker cp ${DOCKER_ID}:/workdir/test /tmp/test
  #- docker ps
  #- cat /tmp/test
  #- docker run ${DOCKER_ID} /bin/bash -c "hostname"
  #- docker stop "${DOCKER_ID}"
