sudo: required
language: c
services:
  - docker

env:
  - DIST_NAME: ubuntu
    DIST_VERS: 16.04
    TAG: liblightnvm
#  - DIST_NAME: ubuntu
#    DIST_VERS: 14.04
#  - DIST_NAME: ubuntu
#    DIST_VERS: 12.04

before_install:
  - docker pull ${DIST_NAME}:${DIST_VERS}
  - docker build --rm=true --file=ci/DockerFile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} .

script:
  - DOCKER_ID_FILE=$(mktemp)
  - docker run --detach ${DIST_NAME}-${DIST_VERS}:${TAG} > "${DOCKER_ID_FILE}"
  - DOCKER_ID=$(cat ${DOCKER_ID_FILE})
  - docker ps
  - docker run ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash -c "ls"
  - docker run ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash -c "hostname"
  - docker run ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash -c "hostname"
  - docker run ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash -c "hostname"
  - docker run ${DIST_NAME}-${DIST_VERS}:${TAG} /bin/bash -c "echo '$RANDOM' > test"
  - docker ps
  - docker cp ${DOCKER_ID}:/workdir/test /tmp/test
  - docker ps
  - cat /tmp/test
  - docker run ${DOCKER_ID} /bin/bash -c "hostname"
  - docker stop "${DOCKER_ID}"
